import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { BrowserOSAgentProgram } from '@browseros/shared/types/role-programs'
import type { OpenClawProgramStorage } from './program-storage'

function describeSchedule(program: BrowserOSAgentProgram): string {
  switch (program.schedule.type) {
    case 'manual':
      return 'manual only'
    case 'daily': {
      const weekdaySummary = program.schedule.daysOfWeek?.length
        ? ` on ${program.schedule.daysOfWeek.join(', ')}`
        : ''
      return `daily at ${program.schedule.time}${weekdaySummary}`
    }
    case 'hourly':
      return `every ${program.schedule.interval} hour(s)`
    case 'minutes':
      return `every ${program.schedule.interval} minute(s)`
  }
}

function buildProgramsMd(programs: BrowserOSAgentProgram[]): string {
  const sections =
    programs.length === 0
      ? ['No BrowserOS-managed programs configured yet.']
      : programs.map(
          (program) => `## ${program.name}
- Status: ${program.enabled ? 'enabled' : 'disabled'}
- Schedule: ${describeSchedule(program)}
- Goal: ${program.description}
- Prompt: ${program.prompt}
`,
        )

  return `# BrowserOS Programs

This file is generated by BrowserOS. Edit program settings in BrowserOS, not here.

${sections.join('\n')}
`
}

function buildStandingOrdersMd(programs: BrowserOSAgentProgram[]): string {
  const sections = programs.flatMap((program) => {
    if (program.standingOrders.length === 0) return []
    const lines = program.standingOrders
      .map(
        (order) =>
          `- ${order.title} (${order.enabled ? 'enabled' : 'disabled'}): ${order.instruction}`,
      )
      .join('\n')

    return [`## ${program.name}\n${lines}`]
  })

  return `# Standing Orders

This file is generated by BrowserOS. Edit standing orders in BrowserOS, not here.

${sections.length > 0 ? sections.join('\n\n') : 'No standing orders configured yet.'}
`
}

function buildProgramsMetadata(
  agentName: string,
  programs: BrowserOSAgentProgram[],
): string {
  return `${JSON.stringify(
    {
      version: 1,
      agentName,
      programs: programs.map((program) => ({
        id: program.id,
        name: program.name,
        enabled: program.enabled,
        schedule: program.schedule,
        updatedAt: program.updatedAt,
      })),
    },
    null,
    2,
  )}\n`
}

export class OpenClawProgramMaterializer {
  constructor(
    private openclawDir: string,
    private storage: OpenClawProgramStorage,
  ) {}

  private getHostWorkspaceDir(agentName: string): string {
    return join(
      this.openclawDir,
      agentName === 'main' ? 'workspace' : `workspace-${agentName}`,
    )
  }

  async syncAgentPrograms(agentName: string): Promise<void> {
    const programs = await this.storage.listPrograms(agentName)
    const workspaceDir = this.getHostWorkspaceDir(agentName)
    await mkdir(workspaceDir, { recursive: true })

    await Promise.all([
      writeFile(join(workspaceDir, 'PROGRAMS.md'), buildProgramsMd(programs)),
      writeFile(
        join(workspaceDir, 'STANDING-ORDERS.md'),
        buildStandingOrdersMd(programs),
      ),
      writeFile(
        join(workspaceDir, '.browseros-programs.json'),
        buildProgramsMetadata(agentName, programs),
      ),
    ])
  }
}
